menubar: false
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
theme_advanced_buttons3_add:
  - tablecontrols 
  - fullscreen
  
plugins:
  - table
  - fullscreen
  - advlist
  - autolink
  - link
  - image
  - lists
  - charmap
  - print
  - preview
  - hr
  - anchor
  - pagebreak
  - spellchecker
  - searchreplace
  - wordcount
  - visualblocks
  - visualchars
  - code
  - insertdatetime
  - media
  - nonbreaking
  - contextmenu
  - directionality
  - emoticons
  - template
  - textcolor
  - paste
  - fullpage
  - textcolor